export type WorkflowStatus = "RUNNING" | "RETRY_REQUIRED" | "AWAITING_APPROVAL" | "RELEASE_READY" | "SAFE_STOP" | "WAITING_CLARIFICATION";
export type TaskStatus = "pending" | "complete";

export interface WorkflowEvent { timestamp: string; stage: string; agent: string; action: string; status: string; attempt: number; detail?: string | null; }
export interface WorkflowTask { task_id: string; description: string; dependencies: string[]; status: TaskStatus; risk: string; validation: string; }
export interface RequirementAssessment { normalized_requirement: string; requirement_type: string; acceptance_criteria: string[]; ambiguities: string[]; assumptions: string[]; risk_level: string; confidence: number; security_considerations: string[]; non_functional_requirements: string[]; impacted_components: string[]; recommended_next_step: string; source: string; }
export interface Workflow { workflow_id: string; status: WorkflowStatus; current_stage: string; current_agent: string; raw_requirement: string; requirement_version: number; normalized_requirement: string; requirement_type: string; acceptance_criteria: string[]; assessment?: RequirementAssessment | null; node_statuses: Record<string, string>; ambiguities: string[]; assumptions: string[]; risk_level: string; architecture_analysis: Record<string, string | string[]>; tasks: WorkflowTask[]; changed_files: string[]; test_results: Record<string, unknown>; security_results: Record<string, unknown>; retry_count: number; rollback_count: number; approval_status: string; approval_identity?: string | null; decisions: Array<Record<string, string>>; events: WorkflowEvent[]; started_at: string; completed_at?: string | null; }
export interface Metrics { total_workflows: number; successful_workflows: number; running_workflows: number; approval_required: number; safe_stops: number; retry_count: number; rollback_count: number; human_interventions: number; average_duration_seconds: number; }
export interface ShortUrl { short_code: string; short_url: string; original_url: string; expires_at?: string | null; is_active: boolean; click_count: number; }
export interface Analytics { short_code: string; click_count: number; }